### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by rzbuno** [cgomesu/youtube4tvh#1]
I get stuck after the "pip install ." I read a mistake : "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_HK226/pandas/"

**Comment by cgomesu** [comment]
To try to reproduce it, I'm gonna need your Python version (`python --version`) and distro.  I suspect it's an outdated setuptools package, so go ahead and try to update it (`pip install --upgrade setuptools`) and run `pip install .` again.

**Comment by rzbuno** [comment]
I'm on a Pi4 with latest RaspiOS. Python is 2.7.16, it successfully installed setuptools-44.1.1 and I `run pip install .` again. Will keep you updated. Thanks for the quick answer.

**Comment by rzbuno** [comment]
That latest command took a while to complete. Problem is now solved, thanks !
